# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(1024, 600)
        Dialog.setMinimumSize(QtCore.QSize(1024, 600))
        Dialog.setMaximumSize(QtCore.QSize(1280, 600))
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1011, 591))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 9, 361, 541))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setEnabled(False)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 29, 341, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conveyorSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.conveyorSensor.setEnabled(False)
        self.conveyorSensor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.conveyorSensor.setCheckable(False)
        self.conveyorSensor.setObjectName("conveyorSensor")
        self.verticalLayout.addWidget(self.conveyorSensor)
        self.counterSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.counterSensor.setEnabled(False)
        self.counterSensor.setObjectName("counterSensor")
        self.verticalLayout.addWidget(self.counterSensor)
        self.stackerSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.stackerSensor.setEnabled(False)
        self.stackerSensor.setObjectName("stackerSensor")
        self.verticalLayout.addWidget(self.stackerSensor)
        self.halfTurnMotorSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.halfTurnMotorSensor.setEnabled(False)
        self.halfTurnMotorSensor.setObjectName("halfTurnMotorSensor")
        self.verticalLayout.addWidget(self.halfTurnMotorSensor)
        self.checkBox_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout.addWidget(self.checkBox_9)
        self.checkBox_12 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout.addWidget(self.checkBox_12)
        self.pressConveyorStartSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pressConveyorStartSensor.setEnabled(False)
        self.pressConveyorStartSensor.setObjectName("pressConveyorStartSensor")
        self.verticalLayout.addWidget(self.pressConveyorStartSensor)
        self.pressConveyorStopSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pressConveyorStopSensor.setEnabled(False)
        self.pressConveyorStopSensor.setObjectName("pressConveyorStopSensor")
        self.verticalLayout.addWidget(self.pressConveyorStopSensor)
        self.pressTopHomeSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pressTopHomeSensor.setEnabled(False)
        self.pressTopHomeSensor.setObjectName("pressTopHomeSensor")
        self.verticalLayout.addWidget(self.pressTopHomeSensor)
        self.pressSideHomeSensor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pressSideHomeSensor.setEnabled(False)
        self.pressSideHomeSensor.setObjectName("pressSideHomeSensor")
        self.verticalLayout.addWidget(self.pressSideHomeSensor)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(379, 19, 281, 251))
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_4.setEnabled(True)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(9, 29, 261, 211))
        self.formLayoutWidget_4.setStyleSheet("")
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_8.setEnabled(True)
        self.label_8.setMinimumSize(QtCore.QSize(0, 100))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_9.setEnabled(True)
        self.label_9.setMinimumSize(QtCore.QSize(0, 100))
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.temp0 = QtWidgets.QLCDNumber(self.formLayoutWidget_4)
        self.temp0.setEnabled(True)
        self.temp0.setMinimumSize(QtCore.QSize(0, 100))
        self.temp0.setStyleSheet("")
        self.temp0.setSmallDecimalPoint(False)
        self.temp0.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.temp0.setObjectName("temp0")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.temp0)
        self.temp1 = QtWidgets.QLCDNumber(self.formLayoutWidget_4)
        self.temp1.setEnabled(True)
        self.temp1.setMinimumSize(QtCore.QSize(0, 100))
        self.temp1.setStyleSheet("")
        self.temp1.setSmallDecimalPoint(False)
        self.temp1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.temp1.setProperty("value", 0.0)
        self.temp1.setProperty("intValue", 0)
        self.temp1.setObjectName("temp1")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.temp1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 373, 395))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setSpacing(24)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.slatLengthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slatLengthSpinBox.sizePolicy().hasHeightForWidth())
        self.slatLengthSpinBox.setSizePolicy(sizePolicy)
        self.slatLengthSpinBox.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.slatLengthSpinBox.setFont(font)
        self.slatLengthSpinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.slatLengthSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.slatLengthSpinBox.setAccelerated(True)
        self.slatLengthSpinBox.setMinimum(370)
        self.slatLengthSpinBox.setMaximum(2000)
        self.slatLengthSpinBox.setProperty("value", 2000)
        self.slatLengthSpinBox.setObjectName("slatLengthSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slatLengthSpinBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(0, 100))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.slatWidthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slatWidthSpinBox.sizePolicy().hasHeightForWidth())
        self.slatWidthSpinBox.setSizePolicy(sizePolicy)
        self.slatWidthSpinBox.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.slatWidthSpinBox.setFont(font)
        self.slatWidthSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.slatWidthSpinBox.setAccelerated(True)
        self.slatWidthSpinBox.setMinimum(10)
        self.slatWidthSpinBox.setMaximum(120)
        self.slatWidthSpinBox.setObjectName("slatWidthSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.slatWidthSpinBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(0, 100))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.slatHeightSpinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slatHeightSpinBox.sizePolicy().hasHeightForWidth())
        self.slatHeightSpinBox.setSizePolicy(sizePolicy)
        self.slatHeightSpinBox.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.slatHeightSpinBox.setFont(font)
        self.slatHeightSpinBox.setReadOnly(False)
        self.slatHeightSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.slatHeightSpinBox.setAccelerated(True)
        self.slatHeightSpinBox.setProperty("showGroupSeparator", False)
        self.slatHeightSpinBox.setMinimum(10)
        self.slatHeightSpinBox.setMaximum(80)
        self.slatHeightSpinBox.setObjectName("slatHeightSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.slatHeightSpinBox)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(429, -1, 280, 395))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(24)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 100))
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.slatsPerBoardSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slatsPerBoardSpinBox.sizePolicy().hasHeightForWidth())
        self.slatsPerBoardSpinBox.setSizePolicy(sizePolicy)
        self.slatsPerBoardSpinBox.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.slatsPerBoardSpinBox.setFont(font)
        self.slatsPerBoardSpinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.slatsPerBoardSpinBox.setWrapping(False)
        self.slatsPerBoardSpinBox.setFrame(True)
        self.slatsPerBoardSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.slatsPerBoardSpinBox.setAccelerated(True)
        self.slatsPerBoardSpinBox.setProperty("showGroupSeparator", False)
        self.slatsPerBoardSpinBox.setSuffix("")
        self.slatsPerBoardSpinBox.setPrefix("")
        self.slatsPerBoardSpinBox.setMinimum(1)
        self.slatsPerBoardSpinBox.setProperty("value", 3)
        self.slatsPerBoardSpinBox.setObjectName("slatsPerBoardSpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slatsPerBoardSpinBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 100))
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.slatLengthSpinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slatLengthSpinBox_3.sizePolicy().hasHeightForWidth())
        self.slatLengthSpinBox_3.setSizePolicy(sizePolicy)
        self.slatLengthSpinBox_3.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.slatLengthSpinBox_3.setFont(font)
        self.slatLengthSpinBox_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.slatLengthSpinBox_3.setWrapping(False)
        self.slatLengthSpinBox_3.setFrame(True)
        self.slatLengthSpinBox_3.setReadOnly(True)
        self.slatLengthSpinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.slatLengthSpinBox_3.setAccelerated(True)
        self.slatLengthSpinBox_3.setProperty("showGroupSeparator", False)
        self.slatLengthSpinBox_3.setSuffix("")
        self.slatLengthSpinBox_3.setPrefix("")
        self.slatLengthSpinBox_3.setProperty("value", 3)
        self.slatLengthSpinBox_3.setObjectName("slatLengthSpinBox_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.slatLengthSpinBox_3)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 100))
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.slatLengthSpinBox_4 = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slatLengthSpinBox_4.sizePolicy().hasHeightForWidth())
        self.slatLengthSpinBox_4.setSizePolicy(sizePolicy)
        self.slatLengthSpinBox_4.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.slatLengthSpinBox_4.setFont(font)
        self.slatLengthSpinBox_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.slatLengthSpinBox_4.setWrapping(False)
        self.slatLengthSpinBox_4.setFrame(True)
        self.slatLengthSpinBox_4.setReadOnly(True)
        self.slatLengthSpinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.slatLengthSpinBox_4.setAccelerated(True)
        self.slatLengthSpinBox_4.setProperty("showGroupSeparator", False)
        self.slatLengthSpinBox_4.setSuffix("")
        self.slatLengthSpinBox_4.setPrefix("")
        self.slatLengthSpinBox_4.setProperty("value", 3)
        self.slatLengthSpinBox_4.setObjectName("slatLengthSpinBox_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.slatLengthSpinBox_4)
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tab_2)
        self.buttonBox.setGeometry(QtCore.QRect(1070, 500, 181, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(740, 0, 258, 147))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSpacing(24)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(0, 100))
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.slatsPerBoardSpinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slatsPerBoardSpinBox_2.sizePolicy().hasHeightForWidth())
        self.slatsPerBoardSpinBox_2.setSizePolicy(sizePolicy)
        self.slatsPerBoardSpinBox_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.slatsPerBoardSpinBox_2.setFont(font)
        self.slatsPerBoardSpinBox_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.slatsPerBoardSpinBox_2.setWrapping(False)
        self.slatsPerBoardSpinBox_2.setFrame(True)
        self.slatsPerBoardSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.slatsPerBoardSpinBox_2.setAccelerated(True)
        self.slatsPerBoardSpinBox_2.setProperty("showGroupSeparator", False)
        self.slatsPerBoardSpinBox_2.setSuffix("")
        self.slatsPerBoardSpinBox_2.setPrefix("")
        self.slatsPerBoardSpinBox_2.setMinimum(1)
        self.slatsPerBoardSpinBox_2.setMaximum(10000)
        self.slatsPerBoardSpinBox_2.setProperty("value", 18)
        self.slatsPerBoardSpinBox_2.setObjectName("slatsPerBoardSpinBox_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slatsPerBoardSpinBox_2)
        self.gridLayout.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 410, 701, 23))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Stan"))
        self.groupBox_4.setTitle(_translate("Dialog", "Czujniki"))
        self.conveyorSensor.setText(_translate("Dialog", "Czujnik wjazdowy"))
        self.counterSensor.setText(_translate("Dialog", "Czujnik liczący"))
        self.stackerSensor.setText(_translate("Dialog", "Czujnik układarki"))
        self.halfTurnMotorSensor.setText(_translate("Dialog", "Czujnik półobrotu"))
        self.checkBox_9.setText(_translate("Dialog", "Krańcówka rozjazdu min"))
        self.checkBox_12.setText(_translate("Dialog", "Krańcówka rozjazdu max"))
        self.pressConveyorStartSensor.setText(_translate("Dialog", "Prasa taśma start"))
        self.pressConveyorStopSensor.setText(_translate("Dialog", "Prasa taśma stop"))
        self.pressTopHomeSensor.setText(_translate("Dialog", "Prasa ścisk górny początek"))
        self.pressSideHomeSensor.setText(_translate("Dialog", "Prasa ścisk boczny początek"))
        self.checkBox_4.setText(_translate("Dialog", "Taśma oscylacja lewo"))
        self.checkBox_6.setText(_translate("Dialog", "Taśma oscylacja prawo"))
        self.groupBox_5.setTitle(_translate("Dialog", "Temperatura prasy"))
        self.label_8.setText(_translate("Dialog", "Temp0"))
        self.label_9.setText(_translate("Dialog", "Temp1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Wejścia"))
        self.groupBox.setTitle(_translate("Dialog", "Wymiary lamelki"))
        self.label.setText(_translate("Dialog", "Długość"))
        self.slatLengthSpinBox.setSuffix(_translate("Dialog", " mm"))
        self.label_2.setText(_translate("Dialog", "Szerokość"))
        self.slatWidthSpinBox.setSuffix(_translate("Dialog", " mm"))
        self.label_3.setText(_translate("Dialog", "Wysokość"))
        self.slatHeightSpinBox.setSuffix(_translate("Dialog", " mm"))
        self.groupBox_2.setTitle(_translate("Dialog", "Zliczanie"))
        self.label_4.setText(_translate("Dialog", "Lamelki / Płyta"))
        self.label_5.setText(_translate("Dialog", "Płyty / Szereg"))
        self.label_6.setText(_translate("Dialog", "Szeregi / Seria"))
        self.groupBox_3.setTitle(_translate("Dialog", "Ilość docelowa"))
        self.label_7.setText(_translate("Dialog", "Płyty"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Parametry produkcji"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
